name: "Setup TypeDB"
description: "Run TypeDB server in GitHub Actions"

branding:
  icon: "database"
  color: "purple"

inputs:
  typedb_version:
    description: "The version of TypeDB to use, default is latest"
    required: true
    default: "latest"
  typedb_grpc_port:
    description: "TypeDB's port for gRPC connections, default is 1729"
    required: true
    default: "1729"
  typedb_http_port:
    description: "TypeDB's port for HTTP connections, default is 8000"
    required: true
    default: "8000"
  typedb_args:
    description: "Additional arguments to pass to TypeDB"
    required: false

runs:
  using: composite
  steps:
    - name: Install TypeDB
      shell: bash
      run: |
        TYPEDB_VERSION="${{ inputs.typedb_version }}"
        
        if [ "$TYPEDB_VERSION" = "latest" ]; then
          curl -sSL https://typedb.com/install.sh | sh
        else
          curl -sSL https://typedb.com/install.sh | sh -s -- --version ${{ inputs.typedb_version }}
        fi
        
        echo "$HOME/.typedb" >> $GITHUB_PATH

    - name: Run TypeDB
      shell: bash
      run: |
        
        TYPEDB_GRPC_PORT="${{ inputs.typedb_grpc_port }}"
        TYPEDB_HTTP_PORT="${{ inputs.typedb_http_port }}"
        TYPEDB_ARGS="${{ inputs.typedb_args }}"
        
        alias typedb='"typedb.bat"'
        typedb server --server.address="0.0.0.0:$TYPEDB_GRPC_PORT" --server.http.address="0.0.0.0:$TYPEDB_HTTP_PORT" $TYPEDB_ARGS &
        disown %1
