name: CI

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  typedb-setup:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        typedb_version: ["3.4.0", "latest"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    name: Run Action
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Action
        uses: ./
        with:
          typedb_version: ${{ matrix.typedb_version }}
          typedb_args: "--development-mode.enabled=true"

      - name: Retrieve TypeDB version
        run: curl --fail-with-body http://localhost:8000/v1/version
